name: Check compilation

on:
  push:
    branches: [main]
  pull_request:
      # as by default
      types: [opened, synchronize, reopened]

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    environment: test

    steps:
    - name: Checking out
      uses: actions/checkout@v4
    - name: Testing
      run: echo "Testing"

  build:
    name: Build
    runs-on: ubuntu-latest
    environment: production

    steps:
    - name: Checking out
      uses: actions/checkout@v4
    - name: Building
      run: |
        echo $(pwd)
        echo $HOME
        #sudo apt install libopencv-dev
        # sudo apt install libcamera-dev
        #sudo apt install build-essential meson ninja-build libyaml-dev python3-yaml python3-ply python3-jinja2 libssl-dev openssl git
        #git clone https://git.libcamera.org/libcamera/libcamera.git
        #cd ~/libcamera
        #meson build && sudo ninja -C build install
        #cd ~/current
        #mkdir build && cd build && cmake .. && make
      
  execution:
    name: Report
    runs-on: ubuntu-latest
    environment: production

    steps:
    - name: Checking out
      uses: actions/checkout@v4
    - name: Executing program
      run: echo "Executing"
  
