name: Check build/run/tests

on:
  push:
    branches: [main]
  pull_request:
      # as by default
      types: [opened, synchronize, reopened]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    environment: production

    steps:
    - name: Setting up
      run: |
        sudo apt install libboost-program-options-dev libopencv-dev build-essential meson ninja-build libyaml-dev python3-yaml python3-ply python3-jinja2 libssl-dev openssl git
        git clone https://git.libcamera.org/libcamera/libcamera.git
        cd libcamera
        meson build && sudo ninja -C build install
    - name: Checking out
      uses: actions/checkout@v4
    - name: Building target app
      run: |
        cd current
        mkdir build && cd build && cmake .. && make
      
  execution:
    name: Report
    needs: [build]
    runs-on: ubuntu-latest
    environment: production

    steps:
    - name: Checking out
      uses: actions/checkout@v4
    - name: Executing program
      run: echo "Executing"

  test:
    name: Unit tests
    runs-on: ubuntu-latest
    environment: test

    steps:
    - name: Checking out
      uses: actions/checkout@v4
    - name: Building tests
      run: |
        cd current/tests
        mkdir build && cd build && cmake .. && make
    - name: Running tests
      run: |
        ctest --output-on-failure --test-dir current/tests/build/
 
